name: numba-examples
channels:
  - defaults
  - numba

dependencies:
  - python=3.9
  - numba=0.53
  - numba-scipy=0.2
  - scipy
  - icc_rt
  - dask
  - progressbar2
  - colorama
  - tbb
  - matplotlib
  - imageio
  - pip
  - graphviz
  - python-graphviz
  - bokeh
