name: numba-examples
channels:
  - defaults
  - numba

dependencies:
  - python=3.8
  - numba=0.52
  - numba-scipy=0.2
  - scipy
  - icc_rt=2018.0.2
  - dask
  - progressbar2
  - colorama
  - tbb
  - matplotlib
  - imageio
  - pip
  - graphviz
  - python-graphviz
